### ISSUE TITLE
Problem with languages

### ISSUE THREAD

**Issue by davorpeic** [fromtheoutfit/navee#22] opened 2016-11-09 16:18 UTC
Hi,

using latest navee/craft. 

Problem:
My site has 2 languages, for one particular Section I disabled english and using just non-en language, when I create node and try to add structure entries I don't see any entries in the list, as they don't exist, to test, I tried to add entry (the inline option that is offered to create entry on-fly) and I create test entry in english, then that entry shows up. 

My guess is that the Entry modal that opens don't respect the language selected in Navee and shows only english entries or maybe "default" language. 

So if there is no english version of the entry, it is impossible to select it.

thanks
davor

**Comment by monachilada** [comment] 2016-12-29 13:35
I guess this is a duplicate of #9 ?

**Comment by michaelfromtheoutfit** [comment] 2017-01-17 20:04
Yes - closing as duplicate of #9

**Closed as completed by michaelfromtheoutfit** 2017-01-17 20:04 UTC
